replicaCount: 1

image:
  repository: shantalshanty/globetrotter-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: globetrotter.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
